### ISSUE TITLE
Cmake generation does not function correctly when the build directory is different from the working directory

### ISSUE THREAD

**Issue by MikeT01-ux** [AndrewGaspar/cmake-cargo#32]
I get the following error when running cmake:

![image](https://user-images.githubusercontent.com/60152387/88486013-ca95dc00-cf7a-11ea-8682-808cd5c732b9.png)

This might not be an issue, i do not know if this git supports Mac OS.

Configuration:
cmake version 3.17.0
Mac OS 10.15.2 (19C57)

Any idea how to solve this?

**Comment by AndrewGaspar** [comment]
I believe this is an instance of an issue that I've been meaning to fix if you try to initiate the configuration or build from a different directory than the actual build. I'll look into fixing this.

**Comment by AndrewGaspar** [comment]
Otherwise, I currently do tests against macOS, so it's not necessarily a macOS specific issue.

**Comment by AndrewGaspar** [comment]
Check if `AndrewGaspar/build-out-of-working-dir` fixes your problem.

**Comment by MikeT01-ux** [comment]
> 
> 
> Check if `AndrewGaspar/build-out-of-working-dir` fixes your problem.

Yes, works correctly now! Thanks!

**Comment by AndrewGaspar** [comment]
Excellent! I'll close this when I merge the PR.
